#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 30 12:30:51 2021

@author: hagen
"""

from ceilopy import ceilolab as cl
# import smtplib
# from email.mime.text import MIMEText
# import pandas as pd
# import datetime
# import numpy as np
# import traceback

assert(cl.load_config().get('notify', 'email_address') != 'None'), 'No email has been specified, please do so in ~/.ceilopy/config.ini'

clp = cl.Cl51CloudProdProcessor(p2fl_in = '/nfs/grad/Inst/Ceil/SURFRAD/',
                                p2fl_out = '/nfs/iftp/aftp/g-rad/surfrad/ceilometer/cl51_cloud_prod_lev0',
                                hist_file_format = '*_CEILOMETER_1_LEVEL_3*.his',
                                ignore = [],
                                verbose = False,)
clp.process(generate_missing_folders=True, error_handling='return')
clp.notify()

