#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 30 12:30:51 2021

@author: hagen
"""

from ceilopy import ceilolab as cl
# import smtplib
# from email.mime.text import MIMEText
# import pandas as pd
# import datetime
# import numpy as np
# import traceback

assert(cl.load_config().get('notify', 'email_address') != 'None'), 'No email has been specified, please do so in ~/.ceilopy/config.ini'

clp = cl.Cl51CloudProdProcessor(ignore=['plots'], 
                                # verbose=True,
                                p2fl_in='/nfs/grad/gradobs/raw/short_term/sailsplash/Ceil/',
                                p2fl_out='/nfs/iftp/aftp/g-rad/surfrad/ceilometer/cl51_cloud_prod_lev0/',
                                )
clp.process(generate_missing_folders=True, error_handling='return')
clp.notify(subject = 'sail-splash - cl51cloudprod - status: {status} (clean: {no_of_files_processed}; errors: {no_of_errors})')

